### ISSUE TITLE
upgraded elastic and now having issue

### ISSUE THREAD

**Issue by ehmueller** [selivan/kibana-backup-simple#1]
Hey,

Thanks for writing such a great script. I have been using it to backup my 6.6 elastic cluster and I have recently upgraded to elastic 7.1. Ever since I have upgraded, my backups are not working correctly. Here is the output I get. Any idea on what could have went wrong?

# /usr/bin/kibana-backup.py  --kibana-url https://hostname --user kibana --password xxxxx backup
{
    "config": {
        "error": "Forbidden",
        "message": "Unable to find config",
        "statusCode": 403
    },
    "dashboard": {
        "error": "Forbidden",
        "message": "Unable to find dashboard",
        "statusCode": 403
    },
    "index-pattern": {
        "error": "Forbidden",
        "message": "Unable to find index-pattern",
        "statusCode": 403
    },
    "search": {
        "error": "Forbidden",
        "message": "Unable to find search",
        "statusCode": 403
    },
    "timelion-sheet": {
        "error": "Forbidden",
        "message": "Unable to find timelion-sheet",
        "statusCode": 403
    },
    "visualization": {
        "error": "Forbidden",
        "message": "Unable to find visualization",
        "statusCode": 403
    }
}

**Comment by selivan** [comment]
Hi @ehmueller 

I am using this script with Elastic/Kibana 7.2 and it works.

403 code is "Forbidden", looks like you have some kind of authorization on Kibana.

Try querying Kibana API with curl using the same host, port and user/password:

```
curl -X GET https://<host>:<port>/api/features/v1 -H 'kbn-xsrf: true' --user <user>:<password>
```

Will it print results or fail with 403?

**Comment by selivan** [comment]
Also I updated the script a little, may be that will help. I have Kibana without authorization(on localhost, external queries are protected by nginx authorization), so I can not test it.

**Comment by ehmueller** [comment]
Sorry I must had missed that you replied. I have upgraded again and would like to use your script but I am still having the same issue. I tried the latest version of your script but same scenario.

Here is the output from the command you requested. 

 curl -v -X GET https://hostname/api/saved_objects/_find?type=index-pattern -H 'kbn-xsrf: true' --user kibana
Enter host password for user 'kibana':
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 135.91.31.231...
* Connected to hostname (X.X.X.X) port 443 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 596 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: kctnj01vmh01kba.mt.att.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=US,ST=Texas,L=Dallas,O=Services\, Inc.,OU=Labs,CN=hostname
*        start date: Sat, 03 Aug 2019 00:00:00 GMT
*        expire date: Fri, 10 Jul 2020 12:00:00 GMT
*        issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
*        compression: NULL
* ALPN, server accepted to use http/1.1
* Server auth using Basic with user 'kibana'
> GET /api/saved_objects/_find?type=index-pattern HTTP/1.1
> Host: hostname
> Authorization: Basic a2liYW5hOnAweDZUS1RJd29takRNZlg0eGF6bA==
> User-Agent: curl/7.47.0
> Accept: */*
> kbn-xsrf: true
>
< HTTP/1.1 403 Forbidden
< Date: Mon, 09 Mar 2020 21:00:37 GMT
< Server: Apache/2.4.18 (Ubuntu)
< kbn-name: kibana
< kbn-xpack-sig: efa4a0cb558b91694583339976489986
< content-type: application/json; charset=utf-8
< cache-control: no-cache
< content-length: 79
<
* Connection #0 to host hostname left intact
{"statusCode":403,"error":"Forbidden","message":"Unable to find index-pattern"}

**Comment by ehmueller** [comment]
selivan, 

if I enter the wrong Kibana password, I get this response.


{
    "config": {
        "error": "Unauthorized",
        "message": "[security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate={ 0=\"Bearer realm=\\\"security\\\"\" & 1=\"ApiKey\" & 2=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }",
        "statusCode": 401
    },
    "dashboard": {
        "error": "Unauthorized",
        "message": "[security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate={ 0=\"Bearer realm=\\\"security\\\"\" & 1=\"ApiKey\" & 2=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }",
        "statusCode": 401
    },
    "index-pattern": {
        "error": "Unauthorized",
        "message": "[security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate={ 0=\"Bearer realm=\\\"security\\\"\" & 1=\"ApiKey\" & 2=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }",
        "statusCode": 401
    },
    "search": {
        "error": "Unauthorized",
        "message": "[security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate={ 0=\"Bearer realm=\\\"security\\\"\" & 1=\"ApiKey\" & 2=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }",
        "statusCode": 401
    },
    "timelion-sheet": {
        "error": "Unauthorized",
        "message": "[security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate={ 0=\"Bearer realm=\\\"security\\\"\" & 1=\"ApiKey\" & 2=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }",
        "statusCode": 401
    },
    "visualization": {
        "error": "Unauthorized",
        "message": "[security_exception] failed to authenticate user [kibana], with { header={ WWW-Authenticate={ 0=\"Bearer realm=\\\"security\\\"\" & 1=\"ApiKey\" & 2=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }",
        "statusCode": 401
    }
}



If I type in the correct kibana password, I get this response...

{
    "config": {
        "error": "Forbidden",
        "message": "Unable to find config",
        "statusCode": 403
    },
    "dashboard": {
        "error": "Forbidden",
        "message": "Unable to find dashboard",
        "statusCode": 403
    },
    "index-pattern": {
        "error": "Forbidden",
        "message": "Unable to find index-pattern",
        "statusCode": 403
    },
    "search": {
        "error": "Forbidden",
        "message": "Unable to find search",
        "statusCode": 403
    },
    "timelion-sheet": {
        "error": "Forbidden",
        "message": "Unable to find timelion-sheet",
        "statusCode": 403
    },
    "visualization": {
        "error": "Forbidden",
        "message": "Unable to find visualization",
        "statusCode": 403
    }
}



Not sure what changed other than upgrading the software. Maybe the Kibana user needs more privileges to export this data?

thanks
Eric

**Comment by selivan** [comment]
@ehmueller That's strange. What version of Kibana and Elastic do you have?

What does say command:

`curl -v -X GET https://<host>:<port>/api/saved_objects/_find?type=index-pattern -H 'kbn-xsrf: true' --user <user>:<password>`

**Comment by selivan** [comment]
Looks like kibana user doesn't have privileges to use saved-objects API. You are using X-Pack or something like it? Have you tried the same with admin user(or whatever it is called in X-Pack)?

**Comment by ehmueller** [comment]
I am running 7.5.1 now and yes, I am using the x-pack module. There is no admin user, I just tried the elastic user versus the kibana user and that worked. thank you.

**Comment by selivan** [comment]
@ehmueller Please note that I upgraded the script to use Kibana export and import API. Previous version sometimes had trouble restoring backup on new Kibana installation. I advise you to update it.
